2025-05-21 14:00:42,564 - INFO - Fetched JSON from https://raw.githubusercontent.com/dkhamsing/open-source-ios-apps/master/contents.json
2025-05-21 14:02:25,059 - WARNING - Invalid URL: https://github.com/wwdc
2025-05-21 14:17:27,191 - INFO - Fetched JSON from https://raw.githubusercontent.com/dkhamsing/open-source-ios-apps/master/contents.json
2025-05-21 14:18:54,965 - WARNING - Invalid URL: https://github.com/wwdc
2025-05-21 14:20:25,084 - ERROR - Exception for https://github.com/haiwen/seafile-iOS: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=10)
2025-05-21 14:22:01,075 - ERROR - Exception for https://github.com/marty-suzuki/iOSDesignPatternSamples: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/marty-suzuki/iOSDesignPatternSamples (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1058b1d60>: Failed to establish a new connection: [Errno 50] Network is down'))
2025-05-21 14:28:16,517 - ERROR - Exception for https://github.com/MaikCL/PKDex-iOS: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=10)
2025-05-21 14:30:59,153 - INFO - Updated README.md with 931 results
2025-05-21 14:50:01,092 - INFO - Fetched JSON from https://raw.githubusercontent.com/dkhamsing/open-source-ios-apps/master/contents.json
2025-05-21 14:50:01,112 - INFO - Extracted 928 unique GitHub repository links
2025-05-21 14:50:08,121 - INFO - Updated README.md with 10 results
2025-05-21 14:51:37,972 - INFO - Fetched JSON from https://raw.githubusercontent.com/dkhamsing/open-source-ios-apps/master/contents.json
2025-05-21 14:53:00,975 - WARNING - Invalid URL: https://github.com/wwdc
2025-05-21 15:02:53,034 - INFO - Updated README.md with 931 results
2025-05-21 15:05:13,302 - INFO - Fetched JSON from https://raw.githubusercontent.com/dkhamsing/open-source-ios-apps/master/contents.json
2025-05-21 15:06:36,206 - WARNING - Invalid URL: https://github.com/wwdc
2025-05-21 15:16:10,546 - INFO - Updated README.md with 931 results
2025-05-21 15:30:51,130 - INFO - Fetched JSON from https://raw.githubusercontent.com/dkhamsing/open-source-ios-apps/master/contents.json
2025-05-21 15:32:13,032 - WARNING - Invalid URL: https://github.com/wwdc
2025-05-21 15:42:25,988 - INFO - Updated README.md with 931 results
2025-05-21 15:45:24,540 - INFO - Fetched JSON from https://raw.githubusercontent.com/dkhamsing/open-source-ios-apps/master/contents.json
2025-05-21 15:46:48,768 - WARNING - Invalid URL: https://github.com/wwdc
2025-05-21 15:49:54,214 - INFO - Fetched JSON from https://raw.githubusercontent.com/dkhamsing/open-source-ios-apps/master/contents.json
2025-05-21 15:52:57,115 - INFO - Fetched JSON from https://raw.githubusercontent.com/dkhamsing/open-source-ios-apps/master/contents.json
2025-05-21 15:52:57,138 - INFO - Extracted 928 unique GitHub repository links
2025-05-21 15:52:59,249 - INFO - Updated README.md with 10 results
2025-05-21 15:54:08,012 - INFO - Fetched JSON from https://raw.githubusercontent.com/dkhamsing/open-source-ios-apps/master/contents.json
2025-05-21 15:54:29,106 - WARNING - Rate limit exceeded for https://github.com/JakeLin/SwiftLanguageWeather, retrying after delay
2025-05-21 15:54:39,301 - WARNING - Rate limit exceeded for https://github.com/JakeLin/SwiftLanguageWeather, retrying after delay
2025-05-21 15:54:59,496 - WARNING - Rate limit exceeded for https://github.com/JakeLin/SwiftLanguageWeather, retrying after delay
2025-05-21 15:55:42,910 - WARNING - Invalid URL: https://github.com/wwdc
2025-05-21 15:55:59,709 - WARNING - Rate limit exceeded for https://github.com/dkhamsing/osia, retrying after delay
2025-05-21 15:56:09,913 - WARNING - Rate limit exceeded for https://github.com/dkhamsing/osia, retrying after delay
2025-05-21 15:56:30,113 - WARNING - Rate limit exceeded for https://github.com/dkhamsing/osia, retrying after delay
2025-05-21 15:58:34,201 - WARNING - Rate limit exceeded for https://github.com/Augustyniak/FileExplorer, retrying after delay
2025-05-21 15:58:44,403 - WARNING - Rate limit exceeded for https://github.com/Augustyniak/FileExplorer, retrying after delay
2025-05-21 15:59:04,602 - WARNING - Rate limit exceeded for https://github.com/Augustyniak/FileExplorer, retrying after delay
2025-05-21 16:00:00,105 - ERROR - Exception for https://github.com/tirupati17/giphy-mvvm-swift: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=10)
2025-05-21 16:00:02,121 - ERROR - Exception for https://github.com/tirupati17/giphy-mvvm-swift: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/tirupati17/giphy-mvvm-swift (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080191f0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:04,129 - ERROR - Exception for https://github.com/tirupati17/giphy-mvvm-swift: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/tirupati17/giphy-mvvm-swift (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108019b50>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:04,135 - ERROR - Exception for https://github.com/tirupati17/contacts-mvp-swift: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/tirupati17/contacts-mvp-swift (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080294f0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:06,146 - ERROR - Exception for https://github.com/tirupati17/contacts-mvp-swift: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/tirupati17/contacts-mvp-swift (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029e80>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:08,160 - ERROR - Exception for https://github.com/tirupati17/contacts-mvp-swift: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/tirupati17/contacts-mvp-swift (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080297c0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:08,165 - ERROR - Exception for https://github.com/woocommerce/woocommerce-ios: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/woocommerce/woocommerce-ios (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108013310>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:10,170 - ERROR - Exception for https://github.com/woocommerce/woocommerce-ios: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/woocommerce/woocommerce-ios (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108013820>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:12,176 - ERROR - Exception for https://github.com/woocommerce/woocommerce-ios: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/woocommerce/woocommerce-ios (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108032520>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:12,181 - ERROR - Exception for https://github.com/AlphaWallet/alpha-wallet-ios: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/AlphaWallet/alpha-wallet-ios (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108032e80>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:14,193 - ERROR - Exception for https://github.com/AlphaWallet/alpha-wallet-ios: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/AlphaWallet/alpha-wallet-ios (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108030820>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:16,203 - ERROR - Exception for https://github.com/AlphaWallet/alpha-wallet-ios: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/AlphaWallet/alpha-wallet-ios (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108013940>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:16,209 - ERROR - Exception for https://github.com/exantech/exa-wallet-ios: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/exantech/exa-wallet-ios (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108032730>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:18,219 - ERROR - Exception for https://github.com/exantech/exa-wallet-ios: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/exantech/exa-wallet-ios (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080324f0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:20,227 - ERROR - Exception for https://github.com/exantech/exa-wallet-ios: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/exantech/exa-wallet-ios (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080294c0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:20,230 - ERROR - Exception for https://github.com/mecid/swiftui-recipes-app: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/mecid/swiftui-recipes-app (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029a60>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:22,242 - ERROR - Exception for https://github.com/mecid/swiftui-recipes-app: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/mecid/swiftui-recipes-app (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029a60>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:24,252 - ERROR - Exception for https://github.com/mecid/swiftui-recipes-app: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/mecid/swiftui-recipes-app (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080293d0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:24,259 - ERROR - Exception for https://github.com/igravitystudios/matchimals.fun: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/igravitystudios/matchimals.fun (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080325e0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:26,270 - ERROR - Exception for https://github.com/igravitystudios/matchimals.fun: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/igravitystudios/matchimals.fun (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108032760>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:28,280 - ERROR - Exception for https://github.com/igravitystudios/matchimals.fun: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/igravitystudios/matchimals.fun (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108013370>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:28,286 - ERROR - Exception for https://github.com/CoyoteLab/Studies-Siri-Shortcut-iOS-13: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/CoyoteLab/Studies-Siri-Shortcut-iOS-13 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080391f0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:30,297 - ERROR - Exception for https://github.com/CoyoteLab/Studies-Siri-Shortcut-iOS-13: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/CoyoteLab/Studies-Siri-Shortcut-iOS-13 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x105f968b0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:32,308 - ERROR - Exception for https://github.com/CoyoteLab/Studies-Siri-Shortcut-iOS-13: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/CoyoteLab/Studies-Siri-Shortcut-iOS-13 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108013280>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:32,314 - ERROR - Exception for https://github.com/mkhrapov/ultimate-peg-solitaire: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/mkhrapov/ultimate-peg-solitaire (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108032df0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:34,323 - ERROR - Exception for https://github.com/mkhrapov/ultimate-peg-solitaire: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/mkhrapov/ultimate-peg-solitaire (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080322b0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:36,332 - ERROR - Exception for https://github.com/mkhrapov/ultimate-peg-solitaire: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/mkhrapov/ultimate-peg-solitaire (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080298b0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:36,338 - ERROR - Exception for https://github.com/triangledraw/TriangleDraw-iOS: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/triangledraw/TriangleDraw-iOS (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029ee0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:38,349 - ERROR - Exception for https://github.com/triangledraw/TriangleDraw-iOS: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/triangledraw/TriangleDraw-iOS (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029910>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:40,356 - ERROR - Exception for https://github.com/triangledraw/TriangleDraw-iOS: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/triangledraw/TriangleDraw-iOS (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108030b80>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:40,362 - ERROR - Exception for https://github.com/Dimillian/OSRSUI: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Dimillian/OSRSUI (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108032220>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:42,372 - ERROR - Exception for https://github.com/Dimillian/OSRSUI: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Dimillian/OSRSUI (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108032e20>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:44,377 - ERROR - Exception for https://github.com/Dimillian/OSRSUI: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Dimillian/OSRSUI (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080137f0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:44,381 - ERROR - Exception for https://github.com/unixzii/SwiftUI-2048: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/unixzii/SwiftUI-2048 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x105f966a0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:46,391 - ERROR - Exception for https://github.com/unixzii/SwiftUI-2048: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/unixzii/SwiftUI-2048 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x105f96fa0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:48,402 - ERROR - Exception for https://github.com/unixzii/SwiftUI-2048: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/unixzii/SwiftUI-2048 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108013bb0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:48,407 - ERROR - Exception for https://github.com/emoncms/emoncms-ios: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/emoncms/emoncms-ios (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108032610>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:50,415 - ERROR - Exception for https://github.com/emoncms/emoncms-ios: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/emoncms/emoncms-ios (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108030a90>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:52,424 - ERROR - Exception for https://github.com/emoncms/emoncms-ios: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/emoncms/emoncms-ios (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029070>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:52,430 - ERROR - Exception for https://github.com/alfianlosari/CoronaVirusTrackerSwiftUI: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/alfianlosari/CoronaVirusTrackerSwiftUI (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029940>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:54,442 - ERROR - Exception for https://github.com/alfianlosari/CoronaVirusTrackerSwiftUI: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/alfianlosari/CoronaVirusTrackerSwiftUI (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029eb0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:56,452 - ERROR - Exception for https://github.com/alfianlosari/CoronaVirusTrackerSwiftUI: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/alfianlosari/CoronaVirusTrackerSwiftUI (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108030d90>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:56,458 - ERROR - Exception for https://github.com/Ranchero-Software/NetNewsWire: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Ranchero-Software/NetNewsWire (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080320a0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:00:58,466 - ERROR - Exception for https://github.com/Ranchero-Software/NetNewsWire: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Ranchero-Software/NetNewsWire (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080329d0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:00,475 - ERROR - Exception for https://github.com/Ranchero-Software/NetNewsWire: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Ranchero-Software/NetNewsWire (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080138e0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:00,481 - ERROR - Exception for https://github.com/MhdHejazi/CoronaTracker: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/MhdHejazi/CoronaTracker (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x105f96b80>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:02,493 - ERROR - Exception for https://github.com/MhdHejazi/CoronaTracker: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/MhdHejazi/CoronaTracker (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x105f96e50>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:04,504 - ERROR - Exception for https://github.com/MhdHejazi/CoronaTracker: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/MhdHejazi/CoronaTracker (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080135e0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:04,509 - ERROR - Exception for https://github.com/MartinStamenkovski/LibraryGenesis: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/MartinStamenkovski/LibraryGenesis (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108032d90>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:06,520 - ERROR - Exception for https://github.com/MartinStamenkovski/LibraryGenesis: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/MartinStamenkovski/LibraryGenesis (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108030d00>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:08,526 - ERROR - Exception for https://github.com/MartinStamenkovski/LibraryGenesis: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/MartinStamenkovski/LibraryGenesis (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029130>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:08,532 - ERROR - Exception for https://github.com/suicidesafetyplan/safetyplan-ios: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/suicidesafetyplan/safetyplan-ios (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029310>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:10,544 - ERROR - Exception for https://github.com/suicidesafetyplan/safetyplan-ios: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/suicidesafetyplan/safetyplan-ios (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029c70>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:12,560 - ERROR - Exception for https://github.com/suicidesafetyplan/safetyplan-ios: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/suicidesafetyplan/safetyplan-ios (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108030df0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:12,568 - ERROR - Exception for https://github.com/deltachat/deltachat-ios: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/deltachat/deltachat-ios (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108032220>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:14,581 - ERROR - Exception for https://github.com/deltachat/deltachat-ios: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/deltachat/deltachat-ios (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108032e20>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:16,596 - ERROR - Exception for https://github.com/deltachat/deltachat-ios: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/deltachat/deltachat-ios (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108013790>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:16,602 - ERROR - Exception for https://github.com/ColdGrub1384/LibTerm: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/ColdGrub1384/LibTerm (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x105f96d30>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:18,618 - ERROR - Exception for https://github.com/ColdGrub1384/LibTerm: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/ColdGrub1384/LibTerm (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x105f965e0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:20,634 - ERROR - Exception for https://github.com/ColdGrub1384/LibTerm: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/ColdGrub1384/LibTerm (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108013c70>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:20,639 - ERROR - Exception for https://github.com/soroushchehresa/iran-coronavirus: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/soroushchehresa/iran-coronavirus (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108032790>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:22,656 - ERROR - Exception for https://github.com/soroushchehresa/iran-coronavirus: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/soroushchehresa/iran-coronavirus (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108030d90>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:24,663 - ERROR - Exception for https://github.com/soroushchehresa/iran-coronavirus: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/soroushchehresa/iran-coronavirus (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080298b0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:24,669 - ERROR - Exception for https://github.com/KhaosT/open-apollo: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/KhaosT/open-apollo (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029880>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:26,685 - ERROR - Exception for https://github.com/KhaosT/open-apollo: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/KhaosT/open-apollo (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080298e0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:41,062 - ERROR - Exception for https://github.com/KhaosT/open-apollo: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/KhaosT/open-apollo (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080292e0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:41,072 - ERROR - Exception for https://github.com/dkhamsing/covid19.swift: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/dkhamsing/covid19.swift (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108032c10>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:43,083 - ERROR - Exception for https://github.com/dkhamsing/covid19.swift: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/dkhamsing/covid19.swift (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080327f0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:45,094 - ERROR - Exception for https://github.com/dkhamsing/covid19.swift: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/dkhamsing/covid19.swift (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108013d30>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:45,100 - ERROR - Exception for https://github.com/nploi/corona_tracker: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/nploi/corona_tracker (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x105f96d90>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:47,111 - ERROR - Exception for https://github.com/nploi/corona_tracker: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/nploi/corona_tracker (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x105f96760>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:49,121 - ERROR - Exception for https://github.com/nploi/corona_tracker: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/nploi/corona_tracker (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108013a00>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:49,126 - ERROR - Exception for https://github.com/dopebase/messenger-iOS-chat-swift-firestore: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/dopebase/messenger-iOS-chat-swift-firestore (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108032a30>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:51,135 - ERROR - Exception for https://github.com/dopebase/messenger-iOS-chat-swift-firestore: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/dopebase/messenger-iOS-chat-swift-firestore (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108030be0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:53,146 - ERROR - Exception for https://github.com/dopebase/messenger-iOS-chat-swift-firestore: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/dopebase/messenger-iOS-chat-swift-firestore (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029250>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:53,151 - ERROR - Exception for https://github.com/rrroyal/Harbour: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/rrroyal/Harbour (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029820>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:55,163 - ERROR - Exception for https://github.com/rrroyal/Harbour: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/rrroyal/Harbour (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x105f969a0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:57,169 - ERROR - Exception for https://github.com/rrroyal/Harbour: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/rrroyal/Harbour (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029fa0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:57,175 - ERROR - Exception for https://github.com/manolosavi/xFonts: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/manolosavi/xFonts (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080139a0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:01:59,185 - ERROR - Exception for https://github.com/manolosavi/xFonts: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/manolosavi/xFonts (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108030fa0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:01,196 - ERROR - Exception for https://github.com/manolosavi/xFonts: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/manolosavi/xFonts (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108030670>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:01,201 - ERROR - Exception for https://github.com/OpenASL/Fingerspelling-iOS: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/OpenASL/Fingerspelling-iOS (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108032370>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:03,213 - ERROR - Exception for https://github.com/OpenASL/Fingerspelling-iOS: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/OpenASL/Fingerspelling-iOS (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108030520>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:05,220 - ERROR - Exception for https://github.com/OpenASL/Fingerspelling-iOS: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/OpenASL/Fingerspelling-iOS (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108030df0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:05,226 - ERROR - Exception for https://github.com/fromkk/FreeTimePicker: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/fromkk/FreeTimePicker (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108013790>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:07,236 - ERROR - Exception for https://github.com/fromkk/FreeTimePicker: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/fromkk/FreeTimePicker (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080290d0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:09,246 - ERROR - Exception for https://github.com/fromkk/FreeTimePicker: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/fromkk/FreeTimePicker (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029af0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:09,252 - ERROR - Exception for https://github.com/podverse/podverse-rn: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/podverse/podverse-rn (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080324c0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:11,263 - ERROR - Exception for https://github.com/podverse/podverse-rn: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/podverse/podverse-rn (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x105f96310>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:13,271 - ERROR - Exception for https://github.com/podverse/podverse-rn: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/podverse/podverse-rn (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029b20>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:13,277 - ERROR - Exception for https://github.com/iKenndac/Tofu: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/iKenndac/Tofu (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108013d60>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:15,287 - ERROR - Exception for https://github.com/iKenndac/Tofu: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/iKenndac/Tofu (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108013310>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:17,297 - ERROR - Exception for https://github.com/iKenndac/Tofu: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/iKenndac/Tofu (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108030550>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:17,303 - ERROR - Exception for https://github.com/Jigsaw-Code/outline-apps: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Jigsaw-Code/outline-apps (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080320d0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:19,314 - ERROR - Exception for https://github.com/Jigsaw-Code/outline-apps: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Jigsaw-Code/outline-apps (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108030eb0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:21,325 - ERROR - Exception for https://github.com/Jigsaw-Code/outline-apps: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Jigsaw-Code/outline-apps (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108030d90>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:21,332 - ERROR - Exception for https://github.com/carson-katri/reddit-swiftui: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/carson-katri/reddit-swiftui (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108013370>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:23,342 - ERROR - Exception for https://github.com/carson-katri/reddit-swiftui: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/carson-katri/reddit-swiftui (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080298b0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:25,353 - ERROR - Exception for https://github.com/carson-katri/reddit-swiftui: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/carson-katri/reddit-swiftui (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029be0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:25,359 - ERROR - Exception for https://github.com/pedrommcarrasco/ARbusters: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/pedrommcarrasco/ARbusters (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108032490>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:27,371 - ERROR - Exception for https://github.com/pedrommcarrasco/ARbusters: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/pedrommcarrasco/ARbusters (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x105f96850>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:29,382 - ERROR - Exception for https://github.com/pedrommcarrasco/ARbusters: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/pedrommcarrasco/ARbusters (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029760>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:29,390 - ERROR - Exception for https://github.com/devxoul/SwiftUITodo: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/devxoul/SwiftUITodo (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108013fa0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:31,402 - ERROR - Exception for https://github.com/devxoul/SwiftUITodo: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/devxoul/SwiftUITodo (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108013880>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:33,412 - ERROR - Exception for https://github.com/devxoul/SwiftUITodo: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/devxoul/SwiftUITodo (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108030100>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:33,418 - ERROR - Exception for https://github.com/Dimillian/ACHNBrowserUI: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Dimillian/ACHNBrowserUI (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108032e80>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:35,430 - ERROR - Exception for https://github.com/Dimillian/ACHNBrowserUI: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Dimillian/ACHNBrowserUI (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080303a0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:37,440 - ERROR - Exception for https://github.com/Dimillian/ACHNBrowserUI: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Dimillian/ACHNBrowserUI (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108030a00>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:37,446 - ERROR - Exception for https://github.com/marty-suzuki/GitHubSearchWithSwiftUI: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/marty-suzuki/GitHubSearchWithSwiftUI (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108013e20>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:39,456 - ERROR - Exception for https://github.com/marty-suzuki/GitHubSearchWithSwiftUI: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/marty-suzuki/GitHubSearchWithSwiftUI (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029130>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:41,467 - ERROR - Exception for https://github.com/marty-suzuki/GitHubSearchWithSwiftUI: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/marty-suzuki/GitHubSearchWithSwiftUI (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029820>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:41,472 - ERROR - Exception for https://github.com/netguru/baby-monitor-client-ios: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/netguru/baby-monitor-client-ios (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108032b50>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:43,484 - ERROR - Exception for https://github.com/netguru/baby-monitor-client-ios: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/netguru/baby-monitor-client-ios (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x105f96af0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:45,494 - ERROR - Exception for https://github.com/netguru/baby-monitor-client-ios: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/netguru/baby-monitor-client-ios (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080298e0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:45,500 - ERROR - Exception for https://github.com/msal4/royal_news: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/msal4/royal_news (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108013dc0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:47,511 - ERROR - Exception for https://github.com/msal4/royal_news: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/msal4/royal_news (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108013760>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:49,516 - ERROR - Exception for https://github.com/msal4/royal_news: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/msal4/royal_news (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108030af0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:49,522 - ERROR - Exception for https://github.com/fossasia/open-event-organizer-ios: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/fossasia/open-event-organizer-ios (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108032130>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:51,529 - ERROR - Exception for https://github.com/fossasia/open-event-organizer-ios: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/fossasia/open-event-organizer-ios (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108030e80>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:53,539 - ERROR - Exception for https://github.com/fossasia/open-event-organizer-ios: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/fossasia/open-event-organizer-ios (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108030f10>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:53,547 - ERROR - Exception for https://github.com/VamshiIITBHU14/FakeFBWall: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/VamshiIITBHU14/FakeFBWall (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080137f0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:55,557 - ERROR - Exception for https://github.com/VamshiIITBHU14/FakeFBWall: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/VamshiIITBHU14/FakeFBWall (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080291f0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:57,568 - ERROR - Exception for https://github.com/VamshiIITBHU14/FakeFBWall: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/VamshiIITBHU14/FakeFBWall (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029670>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:57,574 - ERROR - Exception for https://github.com/CrunchyBagel/TracePrivately: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/CrunchyBagel/TracePrivately (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080322b0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:02:59,585 - ERROR - Exception for https://github.com/CrunchyBagel/TracePrivately: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/CrunchyBagel/TracePrivately (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x105f96c40>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:01,592 - ERROR - Exception for https://github.com/CrunchyBagel/TracePrivately: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/CrunchyBagel/TracePrivately (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029610>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:01,598 - ERROR - Exception for https://github.com/chuongtrh/palette-from-image: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/chuongtrh/palette-from-image (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108013df0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:03,609 - ERROR - Exception for https://github.com/chuongtrh/palette-from-image: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/chuongtrh/palette-from-image (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108013bb0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:05,618 - ERROR - Exception for https://github.com/chuongtrh/palette-from-image: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/chuongtrh/palette-from-image (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108032e80>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:05,622 - ERROR - Exception for https://github.com/soapyigu/Swift-30-Projects: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/soapyigu/Swift-30-Projects (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080307c0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:07,633 - ERROR - Exception for https://github.com/soapyigu/Swift-30-Projects: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/soapyigu/Swift-30-Projects (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108013e80>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:09,643 - ERROR - Exception for https://github.com/soapyigu/Swift-30-Projects: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/soapyigu/Swift-30-Projects (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080297f0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:09,649 - ERROR - Exception for https://github.com/lucaslimapoa/NewsAPISwift: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/lucaslimapoa/NewsAPISwift (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029340>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:11,659 - ERROR - Exception for https://github.com/lucaslimapoa/NewsAPISwift: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/lucaslimapoa/NewsAPISwift (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108032bb0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:13,669 - ERROR - Exception for https://github.com/lucaslimapoa/NewsAPISwift: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/lucaslimapoa/NewsAPISwift (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108032fd0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:13,674 - ERROR - Exception for https://github.com/gtokman/Restaurant-Viewing-App: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/gtokman/Restaurant-Viewing-App (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108030af0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:15,686 - ERROR - Exception for https://github.com/gtokman/Restaurant-Viewing-App: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/gtokman/Restaurant-Viewing-App (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x105f969a0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:17,694 - ERROR - Exception for https://github.com/gtokman/Restaurant-Viewing-App: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/gtokman/Restaurant-Viewing-App (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080327c0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:17,700 - ERROR - Exception for https://github.com/HassanElDesouky/VoiceMemosClone: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/HassanElDesouky/VoiceMemosClone (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080297c0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:19,710 - ERROR - Exception for https://github.com/HassanElDesouky/VoiceMemosClone: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/HassanElDesouky/VoiceMemosClone (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029400>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:21,721 - ERROR - Exception for https://github.com/HassanElDesouky/VoiceMemosClone: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/HassanElDesouky/VoiceMemosClone (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108013a60>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:21,726 - ERROR - Exception for https://github.com/dkhamsing/news: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/dkhamsing/news (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108030b50>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:23,739 - ERROR - Exception for https://github.com/dkhamsing/news: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/dkhamsing/news (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108013bb0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:25,744 - ERROR - Exception for https://github.com/dkhamsing/news: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/dkhamsing/news (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080291c0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:25,750 - ERROR - Exception for https://github.com/objcio/app-architecture: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/objcio/app-architecture (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029e50>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:27,761 - ERROR - Exception for https://github.com/objcio/app-architecture: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/objcio/app-architecture (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108032fa0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:29,771 - ERROR - Exception for https://github.com/objcio/app-architecture: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/objcio/app-architecture (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108032ac0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:29,777 - ERROR - Exception for https://github.com/alfianlosari/SwiftUI-MovieDB: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/alfianlosari/SwiftUI-MovieDB (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108030910>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:31,788 - ERROR - Exception for https://github.com/alfianlosari/SwiftUI-MovieDB: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/alfianlosari/SwiftUI-MovieDB (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x105f96760>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:33,794 - ERROR - Exception for https://github.com/alfianlosari/SwiftUI-MovieDB: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/alfianlosari/SwiftUI-MovieDB (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108032250>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:33,800 - ERROR - Exception for https://github.com/aranja/rakning-c19-app: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/aranja/rakning-c19-app (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029cd0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:35,810 - ERROR - Exception for https://github.com/aranja/rakning-c19-app: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/aranja/rakning-c19-app (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029a90>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:37,821 - ERROR - Exception for https://github.com/aranja/rakning-c19-app: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/aranja/rakning-c19-app (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108013b20>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:37,826 - ERROR - Exception for https://github.com/covid19cz/erouska-ios: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/covid19cz/erouska-ios (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108030ac0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:39,838 - ERROR - Exception for https://github.com/covid19cz/erouska-ios: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/covid19cz/erouska-ios (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108013a30>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:41,849 - ERROR - Exception for https://github.com/covid19cz/erouska-ios: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/covid19cz/erouska-ios (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029430>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:41,855 - ERROR - Exception for https://github.com/MohGovIL/hamagen-react-native: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/MohGovIL/hamagen-react-native (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080297f0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:43,866 - ERROR - Exception for https://github.com/MohGovIL/hamagen-react-native: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/MohGovIL/hamagen-react-native (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108032af0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:45,876 - ERROR - Exception for https://github.com/MohGovIL/hamagen-react-native: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/MohGovIL/hamagen-react-native (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108032a00>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:45,883 - ERROR - Exception for https://github.com/theindianappguy/FlutterNewsApp: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/theindianappguy/FlutterNewsApp (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080304c0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:47,896 - ERROR - Exception for https://github.com/theindianappguy/FlutterNewsApp: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/theindianappguy/FlutterNewsApp (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x105f96970>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:49,906 - ERROR - Exception for https://github.com/theindianappguy/FlutterNewsApp: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/theindianappguy/FlutterNewsApp (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108032a60>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:49,912 - ERROR - Exception for https://github.com/alfianlosari/SwiftUICDExpenseTrackerCompleted: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/alfianlosari/SwiftUICDExpenseTrackerCompleted (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029f10>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:51,919 - ERROR - Exception for https://github.com/alfianlosari/SwiftUICDExpenseTrackerCompleted: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/alfianlosari/SwiftUICDExpenseTrackerCompleted (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029d60>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:53,926 - ERROR - Exception for https://github.com/alfianlosari/SwiftUICDExpenseTrackerCompleted: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/alfianlosari/SwiftUICDExpenseTrackerCompleted (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108013ac0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:53,933 - ERROR - Exception for https://github.com/alfianlosari/CoronaVirusTrackerFlutter: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/alfianlosari/CoronaVirusTrackerFlutter (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1080302b0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:55,939 - ERROR - Exception for https://github.com/alfianlosari/CoronaVirusTrackerFlutter: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/alfianlosari/CoronaVirusTrackerFlutter (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108013ee0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:57,950 - ERROR - Exception for https://github.com/alfianlosari/CoronaVirusTrackerFlutter: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/alfianlosari/CoronaVirusTrackerFlutter (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029f70>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:57,956 - ERROR - Exception for https://github.com/Clean-Swift/CleanStore: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Clean-Swift/CleanStore (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029c10>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:03:59,966 - ERROR - Exception for https://github.com/Clean-Swift/CleanStore: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Clean-Swift/CleanStore (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108032dc0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:04:01,973 - ERROR - Exception for https://github.com/Clean-Swift/CleanStore: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Clean-Swift/CleanStore (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108032160>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:04:01,980 - ERROR - Exception for https://github.com/rodydavis/gmail_clone: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/rodydavis/gmail_clone (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108030b80>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:04:03,987 - ERROR - Exception for https://github.com/rodydavis/gmail_clone: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/rodydavis/gmail_clone (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x105f969a0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:04:05,993 - ERROR - Exception for https://github.com/rodydavis/gmail_clone: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/rodydavis/gmail_clone (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108032610>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:04:06,000 - ERROR - Exception for https://github.com/kwonye/calcupad: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/kwonye/calcupad (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108029fa0>: Failed to resolve 'api.github.com' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-21 16:04:21,376 - ERROR - Exception for https://github.com/mathieudutour/TimeLines: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2025-05-21 16:06:00,558 - WARNING - Rate limit exceeded for https://github.com/niazoff/Chat, retrying after delay
2025-05-21 16:06:57,218 - WARNING - Rate limit exceeded for https://github.com/ProtonVPN/ios-mac-app, retrying after delay
2025-05-21 16:07:07,659 - WARNING - Rate limit exceeded for https://github.com/ProtonVPN/ios-mac-app, retrying after delay
2025-05-21 16:08:10,321 - WARNING - Rate limit exceeded for https://github.com/pitt500/OnlineStoreTCA, retrying after delay
2025-05-21 16:08:21,386 - WARNING - Rate limit exceeded for https://github.com/pitt500/OnlineStoreTCA, retrying after delay
2025-05-21 16:09:28,277 - WARNING - Rate limit exceeded for https://github.com/c-villain/SneakerShop, retrying after delay
2025-05-21 16:09:38,698 - WARNING - Rate limit exceeded for https://github.com/c-villain/SneakerShop, retrying after delay
2025-05-21 16:11:18,810 - ERROR - Exception for https://github.com/c-villain/SneakerShop: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2025-05-21 16:11:38,731 - ERROR - Exception for https://github.com/adamlyttleapps/OpenAI-Wrapper-SwiftUI: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=10)
2025-05-21 16:12:24,051 - ERROR - Exception for https://github.com/denissimon/distributed-model-training: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=10)
2025-05-21 16:12:46,065 - ERROR - Exception for https://github.com/denissimon/distributed-model-training: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/denissimon/distributed-model-training (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x108029400>, 'Connection to api.github.com timed out. (connect timeout=10)'))
2025-05-21 16:14:40,245 - INFO - Updated README.md with 931 results
